// Pack de recettes françaises curées, bundlé en local (hors-ligne).
// Les noms d'ingrédients correspondent au catalogue (curé + CIQUAL) pour que
// les macros se calculent automatiquement à l'import. Unités : g, ml, pc,
// « cuillère » (c. à soupe ≈ 15 g), « cup » (c. à café ≈ 5 g).

import type { DraftRecipe } from './recipeImport'

export const RECIPE_PACK: DraftRecipe[] = [
  {
    name: 'Omelette nature',
    description: 'Le classique express, moelleux à cœur.',
    servings: 1, prep_time: 5, cook_time: 5, tags: ['Rapide', 'Végétarien', 'Petit-déj'],
    ingredients: [
      { name: 'Œufs', quantity: 3, unit: 'pc' },
      { name: 'Beurre', quantity: 10, unit: 'g' },
      { name: 'Sel fin', quantity: 1, unit: 'cup' },
      { name: 'Poivre noir', quantity: 1, unit: 'cup' },
    ],
    steps: [
      'Battre les œufs avec le sel et le poivre.',
      'Faire fondre le beurre dans une poêle à feu moyen.',
      'Verser les œufs, ramener les bords vers le centre à la spatule.',
      'Plier l\'omelette quand le dessus est encore baveux et servir.',
    ],
  },
  {
    name: 'Pâtes à la carbonara',
    description: 'Vraie carbonara crémeuse sans crème : œufs et parmesan.',
    servings: 2, prep_time: 10, cook_time: 15, tags: ['Pâtes', 'Rapide'],
    ingredients: [
      { name: 'Spaghetti', quantity: 200, unit: 'g' },
      { name: 'Lardons', quantity: 120, unit: 'g' },
      { name: 'Œufs', quantity: 2, unit: 'pc' },
      { name: 'Parmesan', quantity: 50, unit: 'g' },
      { name: 'Poivre noir', quantity: 1, unit: 'cup' },
    ],
    steps: [
      'Cuire les spaghetti al dente dans l\'eau bouillante salée.',
      'Faire revenir les lardons à sec jusqu\'à coloration.',
      'Mélanger œufs, parmesan râpé et poivre dans un bol.',
      'Hors du feu, mêler pâtes égouttées, lardons et appareil aux œufs.',
      'Détendre avec un peu d\'eau de cuisson et servir aussitôt.',
    ],
  },
  {
    name: 'Riz cantonais',
    description: 'Riz sauté aux œufs, jambon et petits pois.',
    servings: 2, prep_time: 10, cook_time: 15, tags: ['Riz', 'Rapide'],
    ingredients: [
      { name: 'Riz', quantity: 200, unit: 'g' },
      { name: 'Œufs', quantity: 2, unit: 'pc' },
      { name: 'Jambon blanc', quantity: 100, unit: 'g' },
      { name: 'Petit pois', quantity: 100, unit: 'g' },
      { name: 'Oignon', quantity: 1, unit: 'pc' },
      { name: 'Sauce soja', quantity: 2, unit: 'cuillère' },
    ],
    steps: [
      'Cuire le riz puis le laisser refroidir.',
      'Brouiller les œufs dans un wok, réserver.',
      'Faire revenir l\'oignon émincé, le jambon en dés et les petits pois.',
      'Ajouter le riz et la sauce soja, sauter à feu vif.',
      'Incorporer les œufs, mélanger et servir.',
    ],
  },
  {
    name: 'Poulet rôti aux légumes',
    description: 'Blanc de poulet et légumes rôtis au four.',
    servings: 2, prep_time: 15, cook_time: 35, tags: ['Poulet', 'Four'],
    ingredients: [
      { name: 'Blanc de poulet', quantity: 300, unit: 'g' },
      { name: 'Pomme de terre', quantity: 3, unit: 'pc' },
      { name: 'Carotte', quantity: 2, unit: 'pc' },
      { name: 'Oignon', quantity: 1, unit: 'pc' },
      { name: 'Huile d\'olive', quantity: 2, unit: 'cuillère' },
      { name: 'Herbes de Provence', quantity: 1, unit: 'cuillère' },
    ],
    steps: [
      'Préchauffer le four à 200 °C.',
      'Couper les légumes en morceaux, les disposer dans un plat.',
      'Arroser d\'huile, saler, poivrer, parsemer d\'herbes.',
      'Ajouter le poulet et enfourner 35 min en remuant à mi-cuisson.',
    ],
  },
  {
    name: 'Salade de lentilles',
    description: 'Lentilles tièdes, échalote et vinaigrette moutarde.',
    servings: 2, prep_time: 10, cook_time: 25, tags: ['Végétarien', 'Salade'],
    ingredients: [
      { name: 'Lentilles', quantity: 150, unit: 'g' },
      { name: 'Échalote', quantity: 1, unit: 'pc' },
      { name: 'Carotte', quantity: 1, unit: 'pc' },
      { name: 'Moutarde', quantity: 1, unit: 'cuillère' },
      { name: 'Huile d\'olive', quantity: 2, unit: 'cuillère' },
      { name: 'Vinaigre', quantity: 1, unit: 'cuillère' },
    ],
    steps: [
      'Cuire les lentilles 20-25 min à l\'eau, égoutter.',
      'Émincer l\'échalote, râper la carotte.',
      'Préparer la vinaigrette moutarde-huile-vinaigre.',
      'Mélanger le tout et assaisonner.',
    ],
  },
  {
    name: 'Soupe de légumes',
    description: 'Velouté maison réconfortant.',
    servings: 4, prep_time: 15, cook_time: 30, tags: ['Végétarien', 'Soupe'],
    ingredients: [
      { name: 'Pomme de terre', quantity: 2, unit: 'pc' },
      { name: 'Carotte', quantity: 3, unit: 'pc' },
      { name: 'Poireau', quantity: 1, unit: 'pc' },
      { name: 'Oignon', quantity: 1, unit: 'pc' },
      { name: 'Bouillon cube', quantity: 1, unit: 'pc' },
    ],
    steps: [
      'Éplucher et couper tous les légumes.',
      'Faire revenir l\'oignon, ajouter les légumes.',
      'Couvrir d\'eau, ajouter le bouillon, cuire 30 min.',
      'Mixer jusqu\'à consistance lisse et servir.',
    ],
  },
  {
    name: 'Curry de pois chiches',
    description: 'Pois chiches mijotés au lait de coco et curry.',
    servings: 3, prep_time: 10, cook_time: 25, tags: ['Végétarien', 'Mijoté'],
    ingredients: [
      { name: 'Pois chiches', quantity: 250, unit: 'g' },
      { name: 'Lait de coco', quantity: 400, unit: 'ml' },
      { name: 'Tomates concassées', quantity: 200, unit: 'g' },
      { name: 'Oignon', quantity: 1, unit: 'pc' },
      { name: 'Ail', quantity: 2, unit: 'pc' },
      { name: 'Curry', quantity: 2, unit: 'cuillère' },
    ],
    steps: [
      'Faire revenir oignon et ail, ajouter le curry.',
      'Ajouter tomates et pois chiches égouttés.',
      'Verser le lait de coco, mijoter 20 min.',
      'Servir avec du riz.',
    ],
  },
  {
    name: 'Pavé de saumon & riz',
    description: 'Saumon poêlé, riz et filet de citron.',
    servings: 2, prep_time: 5, cook_time: 20, tags: ['Poisson', 'Rapide'],
    ingredients: [
      { name: 'Pavé de saumon', quantity: 2, unit: 'pc' },
      { name: 'Riz', quantity: 150, unit: 'g' },
      { name: 'Citron', quantity: 1, unit: 'pc' },
      { name: 'Huile d\'olive', quantity: 1, unit: 'cuillère' },
    ],
    steps: [
      'Cuire le riz.',
      'Poêler les pavés de saumon 3-4 min par face.',
      'Saler, poivrer, arroser de jus de citron.',
      'Servir avec le riz.',
    ],
  },
  {
    name: 'Quiche lorraine',
    description: 'Pâte, lardons et appareil crémeux.',
    servings: 4, prep_time: 15, cook_time: 35, tags: ['Four', 'Salé'],
    ingredients: [
      { name: 'Pâte brisée', quantity: 1, unit: 'pc' },
      { name: 'Lardons', quantity: 200, unit: 'g' },
      { name: 'Œufs', quantity: 3, unit: 'pc' },
      { name: 'Crème fraîche', quantity: 200, unit: 'ml' },
      { name: 'Emmental râpé', quantity: 80, unit: 'g' },
    ],
    steps: [
      'Préchauffer le four à 200 °C, foncer un moule avec la pâte.',
      'Faire revenir les lardons, les répartir sur la pâte.',
      'Battre œufs et crème, saler peu, poivrer.',
      'Verser l\'appareil, parsemer d\'emmental.',
      'Cuire 30-35 min jusqu\'à dorure.',
    ],
  },
  {
    name: 'Crêpes',
    description: 'Pâte à crêpes maison inratable.',
    servings: 4, prep_time: 10, cook_time: 20, tags: ['Dessert', 'Sucré'],
    ingredients: [
      { name: 'Farine', quantity: 250, unit: 'g' },
      { name: 'Œufs', quantity: 3, unit: 'pc' },
      { name: 'Lait', quantity: 500, unit: 'ml' },
      { name: 'Sucre', quantity: 2, unit: 'cuillère' },
      { name: 'Beurre', quantity: 30, unit: 'g' },
    ],
    steps: [
      'Mélanger farine, sucre et œufs.',
      'Ajouter le lait progressivement pour éviter les grumeaux.',
      'Incorporer le beurre fondu, laisser reposer 30 min.',
      'Cuire chaque crêpe dans une poêle chaude légèrement beurrée.',
    ],
  },
  {
    name: 'Ratatouille',
    description: 'Légumes du soleil mijotés.',
    servings: 4, prep_time: 20, cook_time: 40, tags: ['Végétarien', 'Mijoté'],
    ingredients: [
      { name: 'Aubergine', quantity: 1, unit: 'pc' },
      { name: 'Courgette', quantity: 2, unit: 'pc' },
      { name: 'Poivron', quantity: 1, unit: 'pc' },
      { name: 'Tomate', quantity: 3, unit: 'pc' },
      { name: 'Oignon', quantity: 1, unit: 'pc' },
      { name: 'Huile d\'olive', quantity: 3, unit: 'cuillère' },
    ],
    steps: [
      'Couper tous les légumes en dés.',
      'Faire revenir l\'oignon puis chaque légume séparément.',
      'Réunir, ajouter les tomates, saler, herbes.',
      'Mijoter 40 min à feu doux.',
    ],
  },
  {
    name: 'Purée maison',
    description: 'Purée de pommes de terre au beurre.',
    servings: 4, prep_time: 10, cook_time: 25, tags: ['Accompagnement', 'Végétarien'],
    ingredients: [
      { name: 'Pomme de terre', quantity: 800, unit: 'g' },
      { name: 'Lait', quantity: 150, unit: 'ml' },
      { name: 'Beurre', quantity: 40, unit: 'g' },
    ],
    steps: [
      'Cuire les pommes de terre épluchées à l\'eau salée.',
      'Écraser avec le beurre.',
      'Détendre avec le lait chaud, assaisonner.',
    ],
  },
  {
    name: 'Chili con carne',
    description: 'Bœuf, haricots rouges et épices.',
    servings: 4, prep_time: 15, cook_time: 40, tags: ['Mijoté', 'Épicé'],
    ingredients: [
      { name: 'Bœuf haché', quantity: 400, unit: 'g' },
      { name: 'Haricots rouges', quantity: 250, unit: 'g' },
      { name: 'Tomates concassées', quantity: 400, unit: 'g' },
      { name: 'Oignon', quantity: 1, unit: 'pc' },
      { name: 'Cumin', quantity: 1, unit: 'cuillère' },
      { name: 'Paprika', quantity: 1, unit: 'cuillère' },
    ],
    steps: [
      'Faire revenir l\'oignon puis le bœuf haché.',
      'Ajouter épices, tomates et haricots.',
      'Mijoter 35-40 min à feu doux.',
      'Servir avec du riz.',
    ],
  },
  {
    name: 'Gratin de pâtes',
    description: 'Pâtes gratinées au fromage.',
    servings: 4, prep_time: 10, cook_time: 25, tags: ['Pâtes', 'Four'],
    ingredients: [
      { name: 'Pâtes', quantity: 300, unit: 'g' },
      { name: 'Crème liquide', quantity: 200, unit: 'ml' },
      { name: 'Emmental râpé', quantity: 100, unit: 'g' },
      { name: 'Jambon blanc', quantity: 100, unit: 'g' },
    ],
    steps: [
      'Cuire les pâtes al dente.',
      'Mélanger pâtes, crème et jambon en dés.',
      'Verser dans un plat, couvrir d\'emmental.',
      'Gratiner 20 min à 200 °C.',
    ],
  },
  {
    name: 'Porridge banane',
    description: 'Flocons d\'avoine cuits au lait, banane.',
    servings: 1, prep_time: 2, cook_time: 6, tags: ['Petit-déj', 'Végétarien'],
    ingredients: [
      { name: 'Flocons d\'avoine', quantity: 50, unit: 'g' },
      { name: 'Lait', quantity: 200, unit: 'ml' },
      { name: 'Banane', quantity: 1, unit: 'pc' },
      { name: 'Miel', quantity: 1, unit: 'cuillère' },
    ],
    steps: [
      'Chauffer le lait et les flocons 5 min en remuant.',
      'Verser dans un bol, ajouter la banane en rondelles.',
      'Napper de miel.',
    ],
  },
  {
    name: 'Salade composée au thon',
    description: 'Salade fraîche complète.',
    servings: 2, prep_time: 15, cook_time: 0, tags: ['Salade', 'Rapide'],
    ingredients: [
      { name: 'Thon en boîte', quantity: 140, unit: 'g' },
      { name: 'Laitue', quantity: 100, unit: 'g' },
      { name: 'Tomate', quantity: 2, unit: 'pc' },
      { name: 'Maïs', quantity: 100, unit: 'g' },
      { name: 'Œufs', quantity: 2, unit: 'pc' },
      { name: 'Huile d\'olive', quantity: 2, unit: 'cuillère' },
    ],
    steps: [
      'Cuire les œufs durs 9 min, écaler et couper.',
      'Déchirer la salade, couper les tomates.',
      'Assembler salade, thon, maïs, tomates, œufs.',
      'Assaisonner à l\'huile d\'olive.',
    ],
  },
  {
    name: 'Pancakes',
    description: 'Pancakes moelleux du week-end.',
    servings: 2, prep_time: 10, cook_time: 15, tags: ['Petit-déj', 'Sucré'],
    ingredients: [
      { name: 'Farine', quantity: 150, unit: 'g' },
      { name: 'Lait', quantity: 200, unit: 'ml' },
      { name: 'Œufs', quantity: 1, unit: 'pc' },
      { name: 'Sucre', quantity: 1, unit: 'cuillère' },
      { name: 'Levure chimique', quantity: 1, unit: 'cup' },
    ],
    steps: [
      'Mélanger farine, sucre et levure.',
      'Ajouter œuf et lait, fouetter en pâte lisse.',
      'Cuire de petites louches dans une poêle chaude.',
      'Retourner quand des bulles apparaissent.',
    ],
  },
  {
    name: 'Tarte aux pommes',
    description: 'Tarte fine et dorée.',
    servings: 6, prep_time: 20, cook_time: 35, tags: ['Dessert', 'Four'],
    ingredients: [
      { name: 'Pâte feuilletée', quantity: 1, unit: 'pc' },
      { name: 'Pomme', quantity: 4, unit: 'pc' },
      { name: 'Sucre', quantity: 3, unit: 'cuillère' },
      { name: 'Beurre', quantity: 20, unit: 'g' },
    ],
    steps: [
      'Étaler la pâte dans un moule.',
      'Disposer les pommes en lamelles, saupoudrer de sucre.',
      'Parsemer de noisettes de beurre.',
      'Cuire 35 min à 190 °C.',
    ],
  },
  {
    name: 'Houmous',
    description: 'Crème de pois chiches au tahini.',
    servings: 4, prep_time: 10, cook_time: 0, tags: ['Apéro', 'Végétarien'],
    ingredients: [
      { name: 'Pois chiches', quantity: 250, unit: 'g' },
      { name: 'Tahini', quantity: 2, unit: 'cuillère' },
      { name: 'Citron', quantity: 1, unit: 'pc' },
      { name: 'Ail', quantity: 1, unit: 'pc' },
      { name: 'Huile d\'olive', quantity: 2, unit: 'cuillère' },
    ],
    steps: [
      'Mixer les pois chiches égouttés avec le tahini.',
      'Ajouter ail, jus de citron et huile.',
      'Mixer jusqu\'à consistance lisse, ajuster avec un peu d\'eau.',
    ],
  },
  {
    name: 'Œufs brouillés',
    description: 'Œufs brouillés crémeux sur pain grillé.',
    servings: 1, prep_time: 2, cook_time: 5, tags: ['Petit-déj', 'Rapide', 'Végétarien'],
    ingredients: [
      { name: 'Œufs', quantity: 3, unit: 'pc' },
      { name: 'Beurre', quantity: 10, unit: 'g' },
      { name: 'Pain de mie', quantity: 2, unit: 'pc' },
    ],
    steps: [
      'Battre les œufs, saler.',
      'Cuire doucement au beurre en remuant sans cesse.',
      'Retirer encore crémeux, servir sur pain grillé.',
    ],
  },
]
